/**
 * Sprint 10E — Barcode Engine Controller
 * Handles: generation, validation, assignment, lookup, history, print tracking
 * Formats: EAN-13, EAN-8, UPC-A, CODE128, CODE39, QR, INTERNAL
 */
const QRCode  = require('qrcode');
const Barcode = require('../models/Barcode');
const { ok, created, paginated, fail, notFound, serverError } = require('../utils/response');

// ─── Pure barcode algorithms ───────────────────────────────────────────────────

function ean13Checksum(digits12) {
  const d = String(digits12).replace(/\D/g, '').slice(0, 12);
  if (d.length !== 12) return null;
  let sum = 0;
  for (let i = 0; i < 12; i++) sum += Number(d[i]) * (i % 2 === 0 ? 1 : 3);
  return String((10 - (sum % 10)) % 10);
}

function ean8Checksum(digits7) {
  const d = String(digits7).replace(/\D/g, '').slice(0, 7);
  if (d.length !== 7) return null;
  let sum = 0;
  for (let i = 0; i < 7; i++) sum += Number(d[i]) * (i % 2 === 0 ? 3 : 1);
  return String((10 - (sum % 10)) % 10);
}

function upcaChecksum(digits11) {
  const d = String(digits11).replace(/\D/g, '').slice(0, 11);
  if (d.length !== 11) return null;
  let sum = 0;
  for (let i = 0; i < 11; i++) sum += Number(d[i]) * (i % 2 === 0 ? 3 : 1);
  return String((10 - (sum % 10)) % 10);
}

function code128Checksum(str) {
  // Code128-B character set checksum
  let sum = 104; // START_B
  for (let i = 0; i < str.length; i++) {
    const code = str.charCodeAt(i) - 32;
    sum += code * (i + 1);
  }
  return String(sum % 103);
}

function validateFormat(value, format) {
  switch (format) {
    case 'EAN13':   return /^\d{13}$/.test(value);
    case 'EAN8':    return /^\d{8}$/.test(value);
    case 'UPCA':    return /^\d{12}$/.test(value);
    case 'CODE128': return /^[\x20-\x7E]+$/.test(value);
    case 'CODE39':  return /^[A-Z0-9\-\.\ \$\/\+\%]+$/.test(value);
    case 'QR':      return value.length > 0 && value.length <= 2953;
    case 'INTERNAL':return /^[A-Z0-9\-_]+$/.test(value);
    default:        return false;
  }
}

function generateInternalSKU(entityType) {
  const prefix = { product: 'PRD', storage_location: 'BIN', package: 'PKG',
                   shipment: 'SHP', delivery_challan: 'DC', purchase_order: 'PO',
                   dealer_order: 'DO', supplier_order: 'SO', warehouse: 'WH', bin: 'BIN' };
  const p = prefix[entityType] || 'INT';
  const stamp = Date.now().toString(36).toUpperCase();
  const rand  = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `${p}-${stamp}-${rand}`;
}

function generateEAN13(prefix = '890') {
  const base = prefix.slice(0, 3) + String(Date.now()).slice(-9);
  const check = ean13Checksum(base);
  return check !== null ? base + check : null;
}

async function generateQRDataUri(text) {
  return QRCode.toDataURL(text, { errorCorrectionLevel: 'M', margin: 1, width: 200 });
}

// ─── Controllers ───────────────────────────────────────────────────────────────

exports.generateBarcode = async (req, res) => {
  try {
    const { format = 'EAN13', entityType, entityId, label, prefix } = req.body;

    if (!entityType || !entityId) return fail(res, 'entityType and entityId are required');

    let value;
    let checkDigit;
    let qrDataUri;
    let svgData;

    switch (format) {
      case 'EAN13':
        value      = generateEAN13(prefix || '890');
        checkDigit = value?.slice(-1);
        break;
      case 'EAN8': {
        const base7 = String(Date.now()).slice(-7);
        const chk   = ean8Checksum(base7);
        value      = chk !== null ? base7 + chk : null;
        checkDigit = chk;
        break;
      }
      case 'UPCA': {
        const base11 = '0' + String(Date.now()).slice(-10);
        const chk    = upcaChecksum(base11);
        value       = chk !== null ? base11 + chk : null;
        checkDigit  = chk;
        break;
      }
      case 'CODE128':
        value = `MTR-${entityType.toUpperCase().slice(0,3)}-${Date.now().toString(36).toUpperCase()}`;
        checkDigit = code128Checksum(value);
        break;
      case 'CODE39':
        value = `MTR${Date.now().toString(36).toUpperCase().slice(0,8)}`;
        break;
      case 'QR': {
        value      = `https://metro.app/scan?type=${entityType}&id=${entityId}&ts=${Date.now()}`;
        qrDataUri  = await generateQRDataUri(value);
        break;
      }
      case 'INTERNAL':
        value = generateInternalSKU(entityType);
        break;
      default:
        return fail(res, 'Unsupported format');
    }

    if (!value) return fail(res, 'Failed to generate barcode value');

    const existing = await Barcode.findOne({ value, format, isDeleted: false });
    if (existing) return fail(res, 'Barcode value already exists — retry');

    const doc = await Barcode.create({
      value, format, entityType, entityId: entityId,
      label: label || String(entityId),
      checkDigit, qrDataUri, svgData,
      autoGenerated: true,
      generatedBy: req.user?._id,
      history: [{ action: 'generated', entityType, entityId, performedBy: req.user?._id }],
    });

    return created(res, doc, 'Barcode generated successfully');
  } catch (err) {
    if (err.code === 11000) return fail(res, 'Duplicate barcode — retry generation');
    return serverError(res, err);
  }
};

exports.assignBarcode = async (req, res) => {
  try {
    const { value, format, entityType, entityId, label } = req.body;
    if (!value || !format || !entityType || !entityId) return fail(res, 'value, format, entityType, entityId required');

    if (!validateFormat(value, format)) return fail(res, `Invalid value for format ${format}`);

    let qrDataUri;
    if (format === 'QR') qrDataUri = await generateQRDataUri(value);

    const existing = await Barcode.findOne({ value, format, isDeleted: false });
    if (existing) return fail(res, 'Barcode value already registered to another entity');

    const doc = await Barcode.create({
      value, format, entityType, entityId,
      label: label || value,
      qrDataUri,
      autoGenerated: false,
      generatedBy: req.user?._id,
      history: [{ action: 'assigned', entityType, entityId, performedBy: req.user?._id }],
    });

    return created(res, doc, 'Barcode assigned');
  } catch (err) {
    if (err.code === 11000) return fail(res, 'Barcode already in use');
    return serverError(res, err);
  }
};

exports.validateBarcode = async (req, res) => {
  try {
    const { value, format } = req.body;
    if (!value) return fail(res, 'value is required');

    const fmt = format || 'EAN13';
    const formatValid = validateFormat(value, fmt);

    const existing = await Barcode.findOne({ value, isDeleted: false });

    return ok(res, {
      value,
      format: fmt,
      formatValid,
      registered: !!existing,
      barcode: existing || null,
    }, formatValid ? 'Valid' : 'Invalid format');
  } catch (err) {
    return serverError(res, err);
  }
};

exports.lookupBarcode = async (req, res) => {
  try {
    const { value } = req.params;
    const doc = await Barcode.findOne({ value: value.toUpperCase(), isDeleted: false });
    if (!doc) return notFound(res, 'Barcode');
    return ok(res, doc);
  } catch (err) {
    return serverError(res, err);
  }
};

exports.getBarcodes = async (req, res) => {
  try {
    const { page = 1, limit = 20, format, entityType, search, isActive } = req.query;
    const skip = (Number(page) - 1) * Number(limit);
    const filter = { isDeleted: false };
    if (format)     filter.format     = format;
    if (entityType) filter.entityType = entityType;
    if (isActive !== undefined) filter.isActive = isActive === 'true';
    if (search)     filter.$or = [
      { value: { $regex: search, $options: 'i' } },
      { label: { $regex: search, $options: 'i' } },
    ];

    const [data, total] = await Promise.all([
      Barcode.find(filter).sort({ createdAt: -1 }).skip(skip).limit(Number(limit)),
      Barcode.countDocuments(filter),
    ]);

    return paginated(res, data, total, page, limit);
  } catch (err) {
    return serverError(res, err);
  }
};

exports.getBarcodesByEntity = async (req, res) => {
  try {
    const { entityType, entityId } = req.params;
    const docs = await Barcode.find({ entityType, entityId, isDeleted: false }).sort({ createdAt: -1 });
    return ok(res, docs);
  } catch (err) {
    return serverError(res, err);
  }
};

exports.deactivateBarcode = async (req, res) => {
  try {
    const doc = await Barcode.findById(req.params.id);
    if (!doc || doc.isDeleted) return notFound(res, 'Barcode');
    doc.isActive = false;
    doc.history.push({ action: 'deactivated', performedBy: req.user?._id });
    await doc.save();
    return ok(res, doc, 'Barcode deactivated');
  } catch (err) {
    return serverError(res, err);
  }
};

exports.recordPrint = async (req, res) => {
  try {
    const doc = await Barcode.findById(req.params.id);
    if (!doc || doc.isDeleted) return notFound(res, 'Barcode');
    doc.isPrinted   = true;
    doc.printCount += 1;
    doc.lastPrinted = new Date();
    doc.history.push({ action: 'printed', performedBy: req.user?._id });
    await doc.save();
    return ok(res, doc, 'Print recorded');
  } catch (err) {
    return serverError(res, err);
  }
};

exports.generateQR = async (req, res) => {
  try {
    const { text, entityType, entityId, label } = req.body;
    if (!text) return fail(res, 'text is required');

    const qrDataUri = await generateQRDataUri(text);

    let doc = null;
    if (entityType && entityId) {
      const existing = await Barcode.findOne({ value: text, format: 'QR', isDeleted: false });
      if (existing) {
        existing.qrDataUri = qrDataUri;
        await existing.save();
        doc = existing;
      } else {
        doc = await Barcode.create({
          value: text, format: 'QR', entityType, entityId,
          label: label || text.slice(0, 100),
          qrDataUri,
          autoGenerated: true,
          generatedBy: req.user?._id,
          history: [{ action: 'generated', entityType, entityId, performedBy: req.user?._id }],
        });
      }
    }

    return ok(res, { qrDataUri, barcode: doc }, 'QR code generated');
  } catch (err) {
    if (err.code === 11000) {
      // Already exists — return existing
      const existing = await Barcode.findOne({ value: req.body.text, format: 'QR' });
      return ok(res, { qrDataUri: existing?.qrDataUri, barcode: existing });
    }
    return serverError(res, err);
  }
};

exports.getBarcodeStats = async (req, res) => {
  try {
    const [total, byFormat, byEntity, printed, activeCount] = await Promise.all([
      Barcode.countDocuments({ isDeleted: false }),
      Barcode.aggregate([
        { $match: { isDeleted: false } },
        { $group: { _id: '$format', count: { $sum: 1 } } },
        { $sort: { count: -1 } },
      ]),
      Barcode.aggregate([
        { $match: { isDeleted: false } },
        { $group: { _id: '$entityType', count: { $sum: 1 } } },
        { $sort: { count: -1 } },
      ]),
      Barcode.countDocuments({ isDeleted: false, isPrinted: true }),
      Barcode.countDocuments({ isDeleted: false, isActive: true }),
    ]);

    return ok(res, { total, activeCount, printed, byFormat, byEntity });
  } catch (err) {
    return serverError(res, err);
  }
};
