/**
 * RoleRegistry — single source of truth for all 31 enterprise roles.
 * Keys ending in "Key" are pointers into other registry files; they are
 * NOT runtime values.  No filtering logic lives here.
 */

export const ROLES = [
  {
    id: 'super_admin',
    displayName: 'Super Administrator',
    iconName: 'FiShield',
    landingKey: 'dashboard',
    workspaceKey: 'full',
    navigationKey: 'full',
    searchScopeKey: 'enterprise',
    permissionKey: 'superadmin',
    tier: 'system',
    portalType: 'admin',
    flags: { canSwitchRoles: true, canManageUsers: true, canViewAudit: true },
  },
  {
    id: 'admin',
    displayName: 'Administrator',
    iconName: 'FiSettings',
    landingKey: 'dashboard',
    workspaceKey: 'full',
    navigationKey: 'full',
    searchScopeKey: 'enterprise',
    permissionKey: 'admin',
    tier: 'system',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: true, canViewAudit: true },
  },
  {
    id: 'executive',
    displayName: 'Executive',
    iconName: 'FiTrendingUp',
    landingKey: 'bi_exec',
    workspaceKey: 'executive',
    navigationKey: 'executive',
    searchScopeKey: 'analytics',
    permissionKey: 'executive',
    tier: 'leadership',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'finance',
    displayName: 'Finance Manager',
    iconName: 'FiDollarSign',
    landingKey: 'finance',
    workspaceKey: 'finance',
    navigationKey: 'finance',
    searchScopeKey: 'finance',
    permissionKey: 'finance',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'accounts',
    displayName: 'Accounts',
    iconName: 'FiFileText',
    landingKey: 'accounts_receivable',
    workspaceKey: 'accounts',
    navigationKey: 'accounts',
    searchScopeKey: 'finance',
    permissionKey: 'accounts',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'sales',
    displayName: 'Sales Manager',
    iconName: 'FiShoppingBag',
    landingKey: 'dashboard',
    workspaceKey: 'sales',
    navigationKey: 'commerce',
    searchScopeKey: 'commerce',
    permissionKey: 'sales',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'crm',
    displayName: 'CRM Manager',
    iconName: 'FiUsers',
    landingKey: 'sales_agents',
    workspaceKey: 'crm',
    navigationKey: 'crm',
    searchScopeKey: 'crm',
    permissionKey: 'crm',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'procurement',
    displayName: 'Procurement Manager',
    iconName: 'FiPackage',
    landingKey: 'procurement',
    workspaceKey: 'procurement',
    navigationKey: 'supply_chain',
    searchScopeKey: 'supply_chain',
    permissionKey: 'procurement',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'warehouse',
    displayName: 'Warehouse Manager',
    iconName: 'FiArchive',
    landingKey: 'warehouse',
    workspaceKey: 'warehouse',
    navigationKey: 'warehouse',
    searchScopeKey: 'supply_chain',
    permissionKey: 'warehouse',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'inventory',
    displayName: 'Inventory Manager',
    iconName: 'FiLayers',
    landingKey: 'inventory',
    workspaceKey: 'inventory',
    navigationKey: 'inventory',
    searchScopeKey: 'supply_chain',
    permissionKey: 'inventory',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'manufacturing',
    displayName: 'Manufacturing Manager',
    iconName: 'FiCpu',
    landingKey: 'manufacturing',
    workspaceKey: 'manufacturing',
    navigationKey: 'manufacturing',
    searchScopeKey: 'manufacturing',
    permissionKey: 'manufacturing',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'quality',
    displayName: 'Quality Manager',
    iconName: 'FiCheckCircle',
    landingKey: 'qms',
    workspaceKey: 'quality',
    navigationKey: 'quality',
    searchScopeKey: 'manufacturing',
    permissionKey: 'quality',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'service',
    displayName: 'Service Manager',
    iconName: 'FiTool',
    landingKey: 'service',
    workspaceKey: 'service',
    navigationKey: 'service',
    searchScopeKey: 'service',
    permissionKey: 'service',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'projects',
    displayName: 'Project Manager',
    iconName: 'FiFolder',
    landingKey: 'projects',
    workspaceKey: 'projects',
    navigationKey: 'projects',
    searchScopeKey: 'projects',
    permissionKey: 'projects',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'portfolio',
    displayName: 'Portfolio Manager',
    iconName: 'FiGrid',
    landingKey: 'portfolio',
    workspaceKey: 'portfolio',
    navigationKey: 'portfolio',
    searchScopeKey: 'projects',
    permissionKey: 'portfolio',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'hr',
    displayName: 'HR Manager',
    iconName: 'FiUsers',
    landingKey: 'hr',
    workspaceKey: 'hr',
    navigationKey: 'hr',
    searchScopeKey: 'hr',
    permissionKey: 'hr',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'recruitment',
    displayName: 'Recruitment Manager',
    iconName: 'FiUserPlus',
    landingKey: 'recruitment',
    workspaceKey: 'recruitment',
    navigationKey: 'recruitment',
    searchScopeKey: 'hr',
    permissionKey: 'recruitment',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'payroll',
    displayName: 'Payroll Manager',
    iconName: 'FiCreditCard',
    landingKey: 'payroll',
    workspaceKey: 'payroll',
    navigationKey: 'payroll',
    searchScopeKey: 'hr',
    permissionKey: 'payroll',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'employee',
    displayName: 'Employee',
    iconName: 'FiUser',
    landingKey: 'dashboard',
    workspaceKey: 'employee',
    navigationKey: 'employee_ess',
    searchScopeKey: 'ess',
    permissionKey: 'employee',
    tier: 'portal',
    portalType: 'employee',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'dealer',
    displayName: 'Dealer',
    iconName: 'FiTruck',
    landingKey: 'dashboard',
    workspaceKey: 'dealer',
    navigationKey: 'dealer_portal',
    searchScopeKey: 'b2b',
    permissionKey: 'dealer',
    tier: 'portal',
    portalType: 'dealer',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'retailer',
    displayName: 'Retailer',
    iconName: 'FiShoppingCart',
    landingKey: 'dashboard',
    workspaceKey: 'retailer',
    navigationKey: 'dealer_portal',
    searchScopeKey: 'b2b',
    permissionKey: 'dealer',
    tier: 'portal',
    portalType: 'dealer',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'supplier',
    displayName: 'Supplier',
    iconName: 'FiPackage',
    landingKey: 'dashboard',
    workspaceKey: 'supplier',
    navigationKey: 'supplier_portal',
    searchScopeKey: 'supply_chain',
    permissionKey: 'supplier',
    tier: 'portal',
    portalType: 'supplier',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'customer',
    displayName: 'Customer',
    iconName: 'FiShoppingBag',
    landingKey: 'dashboard',
    workspaceKey: 'customer',
    navigationKey: 'customer_portal',
    searchScopeKey: 'commerce',
    permissionKey: 'customer',
    tier: 'portal',
    portalType: 'customer',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'installation_engineer',
    displayName: 'Installation Engineer',
    iconName: 'FiTool',
    landingKey: 'dashboard',
    workspaceKey: 'engineer',
    navigationKey: 'engineer_portal',
    searchScopeKey: 'service',
    permissionKey: 'engineer',
    tier: 'portal',
    portalType: 'engineer',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'technician',
    displayName: 'Technician',
    iconName: 'FiSettings',
    landingKey: 'dashboard',
    workspaceKey: 'technician',
    navigationKey: 'technician_portal',
    searchScopeKey: 'service',
    permissionKey: 'technician',
    tier: 'portal',
    portalType: 'technician',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'business_analyst',
    displayName: 'Business Analyst',
    iconName: 'FiBarChart2',
    landingKey: 'bi_exec',
    workspaceKey: 'analytics',
    navigationKey: 'analytics',
    searchScopeKey: 'analytics',
    permissionKey: 'analyst',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'ai_user',
    displayName: 'AI User',
    iconName: 'FiZap',
    landingKey: 'ai_copilot',
    workspaceKey: 'ai',
    navigationKey: 'ai',
    searchScopeKey: 'analytics',
    permissionKey: 'ai_user',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'bi_user',
    displayName: 'BI User',
    iconName: 'FiPieChart',
    landingKey: 'bi_exec',
    workspaceKey: 'bi',
    navigationKey: 'bi',
    searchScopeKey: 'analytics',
    permissionKey: 'bi_user',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'support',
    displayName: 'Support Agent',
    iconName: 'FiHeadphones',
    landingKey: 'service',
    workspaceKey: 'support',
    navigationKey: 'support',
    searchScopeKey: 'service',
    permissionKey: 'support',
    tier: 'functional',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: false },
  },
  {
    id: 'auditor',
    displayName: 'Auditor',
    iconName: 'FiEye',
    landingKey: 'audit_log',
    workspaceKey: 'auditor',
    navigationKey: 'auditor',
    searchScopeKey: 'enterprise',
    permissionKey: 'auditor',
    tier: 'compliance',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: false, canViewAudit: true },
  },
  {
    id: 'system_administrator',
    displayName: 'System Administrator',
    iconName: 'FiServer',
    landingKey: 'settings',
    workspaceKey: 'sysadmin',
    navigationKey: 'sysadmin',
    searchScopeKey: 'enterprise',
    permissionKey: 'sysadmin',
    tier: 'system',
    portalType: 'admin',
    flags: { canSwitchRoles: false, canManageUsers: true, canViewAudit: true },
  },
];

/** Lookup by id — O(1) after first call via Map. */
const _byId = new Map(ROLES.map(r => [r.id, r]));
export function getRoleById(id) { return _byId.get(id) ?? null; }

/** All admin-portal roles (tier !== 'portal'). */
export const ADMIN_ROLES = ROLES.filter(r => r.portalType === 'admin');

/** External-portal roles (each has its own JWT stack). */
export const PORTAL_ROLES = ROLES.filter(r => r.portalType !== 'admin');
