const mongoose = require('mongoose');
const { Schema } = mongoose;
const ObjectId   = Schema.Types.ObjectId;

// Barcode formats supported by the Metro Appliances platform
const FORMATS = ['EAN13', 'EAN8', 'UPCA', 'CODE128', 'CODE39', 'QR', 'INTERNAL'];

// Entity types that can carry a barcode / QR code
const ENTITY_TYPES = [
  'product', 'storage_location', 'package', 'shipment',
  'delivery_challan', 'purchase_order', 'dealer_order',
  'supplier_order', 'warehouse', 'bin',
];

const historySchema = new Schema({
  action:     { type: String, enum: ['generated', 'assigned', 'reassigned', 'deactivated', 'printed'], required: true },
  entityType: { type: String },
  entityId:   { type: ObjectId },
  performedBy:{ type: ObjectId, ref: 'User' },
  note:       { type: String, trim: true },
  at:         { type: Date, default: Date.now },
}, { _id: false });

const barcodeSchema = new Schema({
  // The barcode value (human-readable code)
  value:      { type: String, required: true, trim: true, uppercase: true },
  format:     { type: String, enum: FORMATS, required: true },

  // What entity this barcode belongs to
  entityType: { type: String, enum: ENTITY_TYPES, required: true },
  entityId:   { type: ObjectId, required: true },

  // Display label (e.g. product name, location code)
  label:      { type: String, trim: true, maxlength: 200 },

  // Generated data
  qrDataUri:  { type: String },           // base64 PNG from qrcode pkg (QR format only)
  svgData:    { type: String },           // SVG string for barcode display
  checkDigit: { type: String, maxlength: 2 },

  // State
  isActive:   { type: Boolean, default: true },
  isPrinted:  { type: Boolean, default: false },
  printCount: { type: Number, default: 0 },
  lastPrinted:{ type: Date },

  // Auto-generated flag
  autoGenerated: { type: Boolean, default: false },
  generatedBy:   { type: ObjectId, ref: 'User' },

  history: [historySchema],
  isDeleted: { type: Boolean, default: false },
}, { timestamps: true });

// One active barcode value per format (no two active QR/EAN barcodes can share same value+format)
barcodeSchema.index({ value: 1, format: 1 }, { unique: true, partialFilterExpression: { isDeleted: false } });
barcodeSchema.index({ entityType: 1, entityId: 1, isDeleted: 1 });
barcodeSchema.index({ entityType: 1, isDeleted: 1 });
barcodeSchema.index({ format: 1, isDeleted: 1 });
barcodeSchema.index({ isActive: 1, isDeleted: 1 });
barcodeSchema.index({ createdAt: -1 });

module.exports = mongoose.model('Barcode', barcodeSchema);
