'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;

const qualityAlertSchema = new Schema({
  alertNumber:    { type: String, unique: true },
  alertType:      { type: String, enum: ['defect_spike','oob_reading','ncr_rate','capa_overdue','audit_finding','calibration_due','supplier_issue','customer_complaint','process_deviation','other'], required: true },
  severity:       { type: String, enum: ['info','warning','critical','emergency'], required: true },
  title:          { type: String, required: true },
  description:    { type: String, default: '' },
  // Source references
  product:        { type: Schema.Types.ObjectId, ref: 'Product' },
  productName:    { type: String, default: '' },
  vendor:         { type: Schema.Types.ObjectId, ref: 'Vendor' },
  vendorName:     { type: String, default: '' },
  factory:        { type: Schema.Types.ObjectId, ref: 'Factory' },
  inspectionLot:  { type: Schema.Types.ObjectId, ref: 'InspectionLot' },
  ncReport:       { type: Schema.Types.ObjectId, ref: 'NCReport' },
  capa:           { type: Schema.Types.ObjectId, ref: 'CAPA' },
  gauge:          { type: Schema.Types.ObjectId, ref: 'Gauge' },
  // Alert data
  metricName:     { type: String, default: '' },
  metricValue:    { type: Number },
  threshold:      { type: Number },
  unit:           { type: String, default: '' },
  // Status
  status:         { type: String, enum: ['open','acknowledged','in_progress','resolved','dismissed'], default: 'open' },
  raisedBy:       { type: Schema.Types.ObjectId, ref: 'User' },
  raisedByName:   { type: String, default: '' },
  acknowledgedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  acknowledgedByName: { type: String, default: '' },
  acknowledgedAt: { type: Date },
  resolvedBy:     { type: Schema.Types.ObjectId, ref: 'User' },
  resolvedByName: { type: String, default: '' },
  resolvedAt:     { type: Date },
  resolution:     { type: String, default: '' },
  autoGenerated:  { type: Boolean, default: false },
  notificationSent: { type: Boolean, default: false },
  tags:           [{ type: String }],
  notes:          { type: String, default: '' },
  isDeleted:      { type: Boolean, default: false },
}, { timestamps: true });

qualityAlertSchema.index({ status: 1, severity: -1 });
qualityAlertSchema.index({ alertType: 1, status: 1 });
qualityAlertSchema.index({ factory: 1, status: 1 });
qualityAlertSchema.index({ severity: 1, createdAt: -1 });

qualityAlertSchema.pre('validate', async function (next) {
  if (this.isNew && !this.alertNumber) {
    const yr = new Date().getFullYear();
    const count = await mongoose.model('QualityAlert').countDocuments();
    this.alertNumber = `QALT-${yr}-${String(count + 1).padStart(5, '0')}`;
  }
  next();
});

module.exports = mongoose.model('QualityAlert', qualityAlertSchema);
